### ISSUE TITLE
The "Download Files Permission" appears to be required

### ISSUE THREAD

**Issue by chrishappy** [WesleyBranton/Website-Blocker#19]
![image](https://user-images.githubusercontent.com/14931423/120553663-9adf0e00-c3ad-11eb-88c4-5fa3571511ba.png)

When installing the plugin, the download files permission appears to still be required.

**Comment by WesleyBranton** [comment]
Not an issue, I just forgot to actually send the updated add-on to the Firefox add-ons platform. Oops! It should be available now.
